<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <RootNamespace>Pdfer.Tests.Unit</RootNamespace>
        <EnableNETAnalyzers>true</EnableNETAnalyzers>

        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="NUnit" />
        <PackageReference Include="NUnit3TestAdapter" />
        <PackageReference Include="NUnit.Analyzers" />
        <PackageReference Include="coverlet.collector" />
        <PackageReference Include="Moq" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Pdfer.Common.Tests\Pdfer.Common.Tests.csproj" />
        <ProjectReference Include="..\Pdfer\Pdfer.csproj" />
    </ItemGroup>

</Project>
